# Generated by Django 2.2.17 on 2021-01-26 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sneakers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_sneakers', to='storeapp.Product'),
        ),
    ]
